version: "3.9"
services:
  app:
    build: .
    image: traffic-detection-analysis
    container_name: traffic-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
    command: bash -lc "./start.sh"

